### ISSUE TITLE
Your Nim questions

### ISSUE THREAD

**Issue by StefanSalewski** [archnim/lna#1]
```
Sadly, it is still very hard to understand some things in Nim documentation, because the information is scattered and difficult to search. I would like to know for example :

    What is the difference between declaring my type as a ref object of RootObj and declaring it as inheritable (with a pragma)
    What is the difference between object of and ref object of (it is explained in tuto part 2, but in only two sentences)
    What is the {.inline.} pragma

And much more. Google helps, but not always. Nim manual doesn't give enough details. 
```

Have you tried reading my book?

I think references have been explained well in the book, and inline also. But of course it may be not good enough still. Some say that I explain already too detailed. For your first question, I think using RootObj or RootRef just saves you from use of inheritable pragma if you need inheritance. Good point, I guess that is missing from the book, I will add it.

**Comment by archnim** [comment]
Sorry my friend, for the delay. Thank you very much for your great help. I had read your book  when I just started Nim, but it was above my level at that time. Then I forgot the address. Through your name, I've found it again, and I'm going to eat it with a great appetite. 😁

**Comment by archnim** [comment]
I've just started a [new project](https://github.com/orgs/orixdb), just to learn. I going to do many mistakes in the source code, and it won't be very performant at first. Please can you please take a look at it from time to time ? Just to give me some advice ? 🙏

I'm @archnim on twitter and telegram. Everybody can write to me. Thanks once more.

**Comment by StefanSalewski** [comment]
>but it was above my level at that time.

That is an interesting statement. My book is intended for a fully unskilled audience, and for kids starting at an age of 14. Some people told me that I would already explain too much, things what everyone knows. So when there is still something that you can not understand, because it is still explained bad, then it makes some sense to tell me. Just open an issue for the github issue tracker. The English language may still be a problem for you, but that is a point that we can not avoid currently. But I think the google translatings from english to german are really not that bad, I tried that with google chrome on android and was very surprised by the good results. The other way, German -> English is not that great, so initially writing is German is not a good alternative for me. 

For your new project, I can not help you -- I have never done serious database works, and I have absolutely now spare time avainable, sorry.

**Comment by archnim** [comment]
Thank you, for the book.it's already a huge help 🙂
